name: CI/Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: ghdl/setup-ghdl-ci@nightly
      with:
        backend: mcode

    - name: Setup Python
      uses: actions/setup-python@v2
    
    - name: Install Requirements
      run: pip install -r requirements.txt
      
    - name: VHDLTest Utility
      run: python -m VHDLTest --config test.yaml --log test.log --junit test.xml --exit-0
      working-directory: example
      env:
        PYTHONPATH: ..
